# Site settings
name: no more expect
email: 1073078763@qq.com
author: Micael Cai
url: ""
resume_site: ""
github: https://github.com/cm3082
baseurl: ""
description: We are only here briefly, and when I'm here I want to allow myself joy!
meta_description: 个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: cm3082

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

